# Generated by Django 3.2.7 on 2022-02-20 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clicks',
            name='changed',
        ),
    ]
